apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  helmVersion: v3
  releaseName: podinfo
  chart:
    git: git@github.com:AshKamdar/learn-gitops.git
    path: kubernetes/helm/charts/podinfo
    ref: master
  values:
    replicaCount: 1
