apiVersion: apiextensions.k8s.io/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:AshKamdar/learn-gitops.git
    path: charts/podinfo
    ref: master
